version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'build(deps)'
    versioning-strategy: increase-if-necessary
    groups:
      prod-deps-major:
        dependency-type: 'production'
        update-types: [major]
      prod-deps-minor:
        dependency-type: 'production'
        update-types: [minor]
      prod-deps-patch:
        dependency-type: 'production'
        update-types: [patch]
      dev-deps-major:
        dependency-type: 'development'
        update-types: [major]
      dev-deps-minor:
        dependency-type: 'development'
        update-types: [minor]
      dev-deps-patch:
        dependency-type: 'development'
        update-types: [patch]
